kaystrobach/TYPO3.piwikintegration

- piwik_patches/plugins/TYPO3Login/Controller.php
- piwik_patches/plugins/TYPO3Login/TYPO3Login.php
Fix for #25. Code taken from newer Piwik versions and carefully adjusted. Makes piwikintegration work with Piwik 2.9.
> Fix exception handling, #25

- README.md
Add info on upgrade. Fixes #26.
> Make README.md more clear

- piwik_patches/plugins/TYPO3Login/TYPO3Login.php
Fix wrong merge of https://github.com/kaystrobach/TYPO3.piwikintegration/commit/bfd9d7677e2307c3e21a167fcd2b0524190a4654
> Fix TYPO3Login.php

- piwik_patches/plugins/TYPO3Login/Auth.php
Make comments match current Piwik versions.
Please merge this one **before you merge the next change**, in which I will make the extension compatible with Piwik 2.11.
> Adjust comments

- piwik_patches/plugins/TYPO3Login/TYPO3Login.php
Fix https://github.com/kaystrobach/TYPO3.piwikintegration/issues/34.
This makes piwikintegration compatible with Piwik 2.11.
Please merge #35 **before** you merge this one.
> Compatibility with Piwik 2.11

- ext_localconf.php
Sorry, I messed this one up when I tried not to commit any whitespace cleanups.
> [BUGFIX] Add missing closing bracket in ext_localconf.php

- piwik_patches/plugins/TYPO3Login/Auth.php
- piwik_patches/plugins/TYPO3Login/Controller.php
- piwik_patches/plugins/TYPO3Login/TYPO3Login.php
Cleanup indentation, remove some outdated comments, adjust login script for new version.
As far as I can tell, the result is working with Piwik 2.14.
> Cleanup and updates for Piwik 2.14

- README.md
- piwik_patches/plugins/TYPO3Login/Auth.php
- piwik_patches/plugins/TYPO3Login/TYPO3Login.php
- piwik_patches/plugins/TYPO3Login/config/config.php
Update authentication to be compatible with Piwik 2.15.
> Add compatibility with Piwik 2.15

- Classes/Lib/Config.php
- README.md
- ext_emconf.php
- piwik_patches/plugins/TYPO3Login/Auth.php
- piwik_patches/plugins/TYPO3Login/Controller.php
- piwik_patches/plugins/TYPO3Login/TYPO3Login.php
This integrates all relevant changes for Piwik 2.16.
> Compatibility with Piwik 2.16

- Classes/Lib/Config.php
Remove Piwik Pro advertisements in some places. For example in the installation screen, the Piwik Pro Ad widget will be removed etc.
> Remove adverts

- README.md
No other changes needed, works that way for 2.17.
> Update for Piwik 2.17

- composer.json
tx_piwikintegration_tracking is not found on composer installation
> Add classmap to autoloader

- Configuration/TCA/Overrides/be_users.php
- Configuration/TCA/Overrides/sys_template.php
- Configuration/TCA/Overrides/tt_content.php
- ext_tables.php
Running piwikintegration currently forces a TCA migration for the field be_user.tx_piwikintegration_api_code.
Fixes #61.
> Prevent TCA migration

- ext_localconf.php
- pi1/class.tx_piwikintegration_pi1_wizicon.php
Do not use the key "icon", which is deprecated since TYPO3 7.
#62
> Update icon registration

- README.md
> Compat with Matomo 3.4 and 3.5 confirmed

- .travis.yml
- Classes/Lib/Config.php
- Classes/Lib/Install.php
- composer.json
- ext_emconf.php
> Replace PATH_site/PATH_typo3

- Classes/Lib/Extmgm.php
- Classes/Lib/Install.php
> Replace constants

- Classes/Lib/Div.php
Call RootlineUtility directly instead.
> Fix deprecation with PageRepository->getRootLine()

- Classes/Lib/Div.php
- Classes/Tracking/Tracking.php
- pi1/class.tx_piwikintegration_flexform.php
> Doctrine: Update exec_SELECTquery, remove deprecations

- Classes/Tracking/Tracking.php
> Replace deprecated beUserLogin

- Classes/Lib/Install.php
Use bootstrap.php to make file integrity check green again.
Fixes #82.
> Make file integrity check green again

- .travis.yml
- README.md
- composer.json
- ext_emconf.php
- ext_localconf.php
- ext_tables.php
- piwik_patches/plugins/TYPO3Login/Auth.php
> Update for TYPO3 10

- Classes/Lib/Config.php
- Classes/Lib/Div.php
- README.md
- ext_emconf.php
- piwik_patches/plugins/TYPO3Login/Auth.php
- piwik_patches/plugins/TYPO3Login/config/config.php
Add compatibility for Matomo 4.
> Compatibility for Matomo 4

- piwik_patches/plugins/TYPO3Login/Controller.php
> Add basic error handling
